/* ============================================================================
   PHASE 17 MIGRATION — dbo.users.user_id is the ONE identity, and
                        dbo.users.email is the ONE university email
   ----------------------------------------------------------------------------
   WHY THIS EXISTS

   Until now the application had two competing identity systems:

     * dbo.users.user_id          — IDENTITY(1,1), generated by SQL Server,
                                    already unique across every role.
     * students.student_number /  — typed in by hand by the administrator on
       instructors.employee_number  the Add Student / Add Instructor form.

   The hand-typed columns are retired. From now on the ONLY visible identity
   is users.user_id, shown as "Student ID" for a STUDENT account and
   "Instructor ID" for an INSTRUCTOR account. Nothing generates an id in Java
   any more: every new account gets its id from this table's IDENTITY column,
   read back with OUTPUT INSERTED.user_id.

   The email address moves to the same place for the same reason: it was
   stored per role (students.email, instructors.email), so "is this email
   already taken?" could only ever be asked one role at a time. dbo.users.email
   gives one global answer. The two per-role columns STAY (they are NOT NULL,
   UNIQUE, and read by many existing queries) and the application keeps them
   in step with users.email inside the same transaction.

   WHAT THIS SCRIPT DOES **NOT** DO — deliberately, and by instruction:
     * It does not DROP any table, column, constraint or index.
     * It does not DELETE, renumber or re-seed anything.
     * It does not change a single existing users.user_id.
     * It does not touch password_hash (BCrypt cannot be computed in T-SQL).
     * It does not create any user account.

   SAFE TO RUN ONCE, AND SAFE TO RE-RUN: every step is guarded by an IF and
   the whole thing runs in one transaction that rolls back on any error.

   HOW TO RUN
     sqlcmd -S "localhost\SQLEXPRESS" -U sa -P <password> -C ^
            -i phase17_user_id_as_the_only_identity.sql
============================================================================ */

USE universitymanagementDB;
GO
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET NOCOUNT ON;
GO

/* -------------------------------------------------------------------- 1.
   dbo.users.email — the single university email address per account.

   Added as NULLable on purpose. ADMIN accounts have no email anywhere in the
   schema to back-fill from, and forcing a made-up address on them would be
   inventing data. Students and instructors are back-filled in step 2 and are
   never null afterwards.

   This runs in its OWN batch, outside the transaction below: a column added
   by ALTER TABLE is not visible to the rest of the batch that adds it, so the
   back-fill could not even be parsed if it sat in here. Adding one NULLable
   column is a metadata-only change and cannot half-happen.                */
IF COL_LENGTH('dbo.users', 'email') IS NULL
BEGIN
    PRINT N'1. Adding dbo.users.email (NVARCHAR(100) NULL).';
    ALTER TABLE dbo.users ADD email NVARCHAR(100) NULL;
END
ELSE
    PRINT N'1. dbo.users.email already exists — nothing to add.';
GO

BEGIN TRY
BEGIN TRANSACTION;

    /* ------------------------------------------------------------------ 2.
       Back-fill users.email from the role tables.

       Every students.user_id and instructors.user_id already points at a real
       users row (verified before writing this script: 0 orphans on either
       side), so this is a straight copy, not a guess. Only rows that are
       still NULL are touched, which is what makes a second run a no-op.    */
    PRINT N'2. Back-filling dbo.users.email from students / instructors.';

    UPDATE u
       SET u.email = s.email
      FROM dbo.users u
      INNER JOIN dbo.students s ON s.user_id = u.user_id
     WHERE u.email IS NULL;

    PRINT N'   students  -> users.email rows updated: ' + CAST(@@ROWCOUNT AS NVARCHAR(10));

    UPDATE u
       SET u.email = i.email
      FROM dbo.users u
      INNER JOIN dbo.instructors i ON i.user_id = u.user_id
     WHERE u.email IS NULL;

    PRINT N'   instructors -> users.email rows updated: ' + CAST(@@ROWCOUNT AS NVARCHAR(10));

    /* ------------------------------------------------------------------ 3.
       Refuse to go on if the back-fill produced a duplicate.

       students.email and instructors.email are each UNIQUE on their own, but
       nothing ever stopped the same address existing once in each table. If
       that has happened the unique index in step 4 would fail; failing HERE
       instead says exactly what is wrong. (Checked before writing: 0 such
       addresses today.)                                                    */
    IF EXISTS (SELECT email FROM dbo.users
                WHERE email IS NOT NULL
                GROUP BY email HAVING COUNT(*) > 1)
    BEGIN
        THROW 51000, N'Two accounts share one email address. Fix it by hand, then re-run.', 1;
    END

    /* ------------------------------------------------------------------ 4.
       One address, one account — enforced by the database, not by Java.

       FILTERED (WHERE email IS NOT NULL) so the ADMIN rows left NULL in
       step 1 do not collide with each other: SQL Server's ordinary UNIQUE
       index treats two NULLs as equal and would allow only one of them.    */
    IF NOT EXISTS (SELECT 1 FROM sys.indexes
                    WHERE name = 'UQ_users_email'
                      AND object_id = OBJECT_ID('dbo.users'))
    BEGIN
        PRINT N'4. Creating filtered unique index UQ_users_email.';
        CREATE UNIQUE NONCLUSTERED INDEX UQ_users_email
            ON dbo.users (email)
            WHERE email IS NOT NULL;
    END
    ELSE
        PRINT N'4. UQ_users_email already exists — nothing to create.';

    /* ------------------------------------------------------------------ 5.
       RETIRED, NOT REMOVED.

       students.student_number and instructors.employee_number are left
       exactly as they are: NOT NULL, UNIQUE, every historic value intact.
       The application no longer shows them, searches them, or asks anybody
       to type one; when it creates a new row it fills the column with
       'U<user_id>' purely to satisfy NOT NULL. Dropping them is a separate
       decision for another day — doing it here could break a report or a
       hand-written query nobody has looked at yet.                         */
    PRINT N'5. students.student_number / instructors.employee_number kept as legacy columns.';

COMMIT TRANSACTION;
PRINT N'--- Phase 17 migration committed. ---';
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    PRINT N'!!! Phase 17 migration ROLLED BACK — nothing was changed. !!!';
    THROW;
END CATCH
GO

/* ---------------------------------------------------------------- verify */
SELECT  (SELECT COUNT(*) FROM dbo.users)                          AS users_total,
        (SELECT COUNT(*) FROM dbo.users WHERE email IS NOT NULL)  AS users_with_email,
        (SELECT COUNT(*) FROM dbo.students)                       AS students_total,
        (SELECT COUNT(*) FROM dbo.instructors)                    AS instructors_total,
        (SELECT COUNT(*) FROM dbo.students  s
           JOIN dbo.users u ON u.user_id = s.user_id
          WHERE u.email <> s.email)                               AS student_email_mismatches,
        (SELECT COUNT(*) FROM dbo.instructors i
           JOIN dbo.users u ON u.user_id = i.user_id
          WHERE u.email <> i.email)                               AS instructor_email_mismatches;
GO
