package com.university.model;

import com.university.enums.UserRole;

import java.time.LocalDateTime;

/**
 * One row of {@code dbo.users}, the single login record per person.
 *
 * <p>{@code userId} is the whole system's one identity. It is generated by
 * SQL Server's IDENTITY column and is what the interface calls "Student ID"
 * on a STUDENT account and "Instructor ID" on an INSTRUCTOR account — there
 * is no second, hand-typed id anywhere.</p>
 *
 * <p>A STUDENT's or INSTRUCTOR's university email and postal address still
 * belong to the person, not the login, and live on {@link Student#getEmail()}/
 * {@link Student#getAddress()} and {@link Instructor#getEmail()}/
 * {@link Instructor#getAddress()} — {@link #email} and {@link #address} here
 * are left {@code null} for those two roles. An ADMIN account has no separate
 * profile row of its own ({@code dbo.admins} was retired), so its own email
 * and address, when set, live directly on this row instead.</p>
 *
 * <p>{@code passwordHash} holds a BCrypt hash. Plain text passwords are never
 * stored in this object or in the database.</p>
 */
public class User {

    private int userId;
    private String username;
    private String passwordHash;
    private UserRole role;
    private boolean active = true;
    private LocalDateTime lastLogin;
    private LocalDateTime createdAt;
    private String email;
    private String address;
    private int failedLoginAttempts;
    private boolean locked;
    private LocalDateTime lockedAt;

    public User() {
    }

    public User(int userId, String username, String passwordHash, UserRole role,
                boolean active, LocalDateTime lastLogin, LocalDateTime createdAt) {
        this.userId = userId;
        this.username = username;
        this.passwordHash = passwordHash;
        this.role = role;
        this.active = active;
        this.lastLogin = lastLogin;
        this.createdAt = createdAt;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public UserRole getRole() {
        return role;
    }

    public void setRole(UserRole role) {
        this.role = role;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public LocalDateTime getLastLogin() {
        return lastLogin;
    }

    public void setLastLogin(LocalDateTime lastLogin) {
        this.lastLogin = lastLogin;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /** Null for STUDENT/INSTRUCTOR — see the class comment. Only ADMIN uses this. */
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /** Null for STUDENT/INSTRUCTOR — see the class comment. Only ADMIN uses this. */
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    /** Consecutive failed sign-in attempts. STUDENT/INSTRUCTOR only; reset to 0 on a successful sign-in. */
    public int getFailedLoginAttempts() {
        return failedLoginAttempts;
    }

    public void setFailedLoginAttempts(int failedLoginAttempts) {
        this.failedLoginAttempts = failedLoginAttempts;
    }

    /** True once 5 consecutive failed attempts have locked this account. Never true for ADMIN. */
    public boolean isLocked() {
        return locked;
    }

    public void setLocked(boolean locked) {
        this.locked = locked;
    }

    /** When the account was locked. Null while unlocked. */
    public LocalDateTime getLockedAt() {
        return lockedAt;
    }

    public void setLockedAt(LocalDateTime lockedAt) {
        this.lockedAt = lockedAt;
    }

    /** The password hash is deliberately left out of this text. */
    @Override
    public String toString() {
        return username + " (" + role + ")";
    }
}
