/* ============================================================================
   SEED 09 -- Notifications
   ONLY INSERT statements below (Section 14 / user requirement).
============================================================================ */

USE universitymanagementDB;
GO
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

BEGIN TRY
BEGIN TRANSACTION;

INSERT INTO dbo.notifications (user_id, title, message, type, is_read)
SELECT u.user_id, v.title, v.msg, v.ntype, v.isread
FROM (VALUES
    (N'k.habib', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.58. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'y.chaaya', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.82. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'd.choueiri', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.71. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N't.chidiac', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.7. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'k.moussawi', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.52. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'n.feghali', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.79. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'n.chalhoub', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.69. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'd.jaber', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.6. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'd.jaber', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.eid', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.56. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'h.eid', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.chidiac', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.habib', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'd.lahoud', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.abourjeily', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'k.raad', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.57. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'k.raad', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'i.rahme', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.kassem', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'k.wehbe2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.fahed', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.78. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N's.fahed', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'g.sfeir', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.zeidan', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.azzi', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.lahoud', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'e.fahed', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.68. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'e.fahed', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'g.chaaya', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'i.chidiac', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'g.geagea', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.frangieh', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.eid', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'y.khalife', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.ghosn3', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.obeid', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.doumit', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.chidiac2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.fares', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.75. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'a.fares', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'z.obeid', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'd.karam', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'k.mansour', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.hamdan', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.saad', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.gemayel', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.baaklini', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'w.fahed', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'y.doumit', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'd.sleiman', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'y.brown', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.tabet', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.choueiri', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.55. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'n.choueiri', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.jureidini', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'g.obeid', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'y.chami', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.nasr', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.azzi', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.assaf', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.naccache', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.zoghbi', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'd.frangieh', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'y.miller', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'k.nasr', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.jaber', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'e.naccache', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'k.chalhoub', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.63. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'k.chalhoub', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.boutros', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.daher', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.sfeir', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.lteif', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'o.khalife', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'o.saad', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.aoun', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.54. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'a.aoun', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.wehbe', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.63. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'h.wehbe', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'g.moussawi', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.frangieh', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.lteif', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.ibrahim', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.52. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'l.ibrahim', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.chalhoub', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.doumit', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.lahoud', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.64. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'f.lahoud', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.chalhoub', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.fares', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.lahoud', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.naccache', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.56. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'j.naccache', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.sleiman', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.rahal2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.maalouf', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'g.matta2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.karam', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.issa', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'i.rahme2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.rahme', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.eid', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.farah', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.kanaan', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'w.gemayel', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'b.azzi', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.davis', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.naccache', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'd.nasr', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'k.rizk', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.tabet', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.johnson', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'g.sfeir2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.karkafi', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.chalhoub', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.johnson', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.raad', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.habib', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'g.bejjani', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'w.davis', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.baaklini', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.gemayel', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.miller', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.daher2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.salloum', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'b.obeid', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.66. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'b.obeid', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'w.chehab', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'g.salloum', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.assaf', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'p.fares', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.nassar', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.abourjeily', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.doumit', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.younes2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.mansour', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.osman', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.barakat', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'i.deeb', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'p.aoun', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.barakat', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.chami', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.zoghbi', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.hobeika', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.yazji', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'k.gemayel', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.farah', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.karam', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.53. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N's.karam', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.abourjeily2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.williams', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.yazji', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.diab', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.geagea', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.lteif', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.osman2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.farah', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.maalouf', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.khalife', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'w.assaf', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.baaklini', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.raad', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.farah', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.58. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'h.farah', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.aoun', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.gemayel', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'z.sabbagh', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.miller2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.tabet', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.gemayel', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.osman', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.sfeir', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.obeid', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.chidiac', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.farah', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'i.doumit', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.gemayel', N'Academic standing: Probation', N'Your cumulative GPA is 1.96. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'n.gemayel', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.fahed', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.nassar', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'k.estephan', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.chaaya', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.maalouf2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'p.jaber', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'k.zeidan', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.77. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'k.zeidan', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'i.diab', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.53. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'i.diab', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.chami', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'b.yazji', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.nasr2', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.57. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'h.nasr2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.bejjani', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.assaf2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.geagea', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.diab', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.58. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'l.diab', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.lteif', N'Congratulations -- Dean''s List', N'Your cumulative GPA is 3.78. You have been placed on the Dean''s List.', N'SUCCESS', 0),
    (N'n.lteif', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'o.diab', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.assaf', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.diab', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.geagea', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.frangieh', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.chehab', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.ghosn', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.raad', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.barakat', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'o.bejjani', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'w.sfeir', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.chidiac3', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.chalhoub', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.baaklini', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.diab', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.osman', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.frangieh2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.chidiac2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.baaklini', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'w.estephan', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.chami2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.smith', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'd.chami', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.baaklini2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.diab', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.salloum', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.hobeika', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.chidiac2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.rahme', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.lahoud', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.sabbagh', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'd.miller', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.chalhoub', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.sfeir', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'w.salloum', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.rizk', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'w.deeb', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.williams', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.brown', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.aoun', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.sleiman', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.feghali', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.azzi', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'o.bejjani2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'e.chidiac', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.doumit', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'i.diab2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'k.doumit', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.farah', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.tabet', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.zoghbi3', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.fares', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'g.choueiri', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'z.rizk', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.habib2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.davis', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.doumit2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'e.brown', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.farah', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.issa', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.mansour', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.saad', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'k.younes', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'e.salloum', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.kassem', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.abourjeily', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.tabet', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'w.chalhoub', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.jaber', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.chami', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'd.fahed', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.jureidini', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.baaklini', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.jaber', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.chalhoub2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.chalhoub', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'y.naccache', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'w.khalife', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'd.rahme', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.smith2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.wehbe', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'i.zoghbi', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.eid2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.chehab', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.eid3', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'd.hamdan', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.jureidini', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.barakat2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'k.zoghbi', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'o.aoun', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'h.assaf', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'b.rahme', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'g.younes', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'e.chehab', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N's.choueiri', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.lahoud', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.kanaan', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'p.habib', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.kassem', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.jaber', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'i.geagea', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'e.moussawi', N'Academic standing: Suspended', N'After a second term on probation your status is now SUSPENDED and you cannot register. Please contact the registrar.', N'WARNING', 0),
    (N't.baaklini2', N'Academic standing: Suspended', N'After a second term on probation your status is now SUSPENDED and you cannot register. Please contact the registrar.', N'WARNING', 0),
    (N'f.younes2', N'Academic standing: Suspended', N'After a second term on probation your status is now SUSPENDED and you cannot register. Please contact the registrar.', N'WARNING', 0),
    (N'e.smith', N'Academic standing: Suspended', N'After a second term on probation your status is now SUSPENDED and you cannot register. Please contact the registrar.', N'WARNING', 0),
    (N'a.rizk', N'Academic standing: Suspended', N'After a second term on probation your status is now SUSPENDED and you cannot register. Please contact the registrar.', N'WARNING', 0),
    (N'm.sabbagh2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'r.farah', N'Academic standing: Suspended', N'After a second term on probation your status is now SUSPENDED and you cannot register. Please contact the registrar.', N'WARNING', 0),
    (N'm.deeb', N'Academic standing: Suspended', N'After a second term on probation your status is now SUSPENDED and you cannot register. Please contact the registrar.', N'WARNING', 0),
    (N'z.kanaan', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.chalhoub', N'Academic standing: Suspended', N'After a second term on probation your status is now SUSPENDED and you cannot register. Please contact the registrar.', N'WARNING', 0),
    (N'm.feghali', N'Academic standing: Suspended', N'After a second term on probation your status is now SUSPENDED and you cannot register. Please contact the registrar.', N'WARNING', 0),
    (N'm.eid', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.chaaya', N'Academic standing: Suspended', N'After a second term on probation your status is now SUSPENDED and you cannot register. Please contact the registrar.', N'WARNING', 0),
    (N'g.ghosn', N'Academic standing: Suspended', N'After a second term on probation your status is now SUSPENDED and you cannot register. Please contact the registrar.', N'WARNING', 0),
    (N'z.ghosn', N'Academic standing: Probation', N'Your cumulative GPA is 0.99. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'z.ghosn', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N't.kassem2', N'Academic standing: Probation', N'Your cumulative GPA is 1.38. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N't.kassem2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'j.zeidan', N'Academic standing: Probation', N'Your cumulative GPA is 1.21. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'j.zeidan', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'a.issa', N'Academic standing: Probation', N'Your cumulative GPA is 0.64. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'a.issa', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'd.fares', N'Academic standing: Probation', N'Your cumulative GPA is 0.19. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'd.fares', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.kanaan', N'Academic standing: Probation', N'Your cumulative GPA is 0.55. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'n.kanaan', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'd.habib', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'k.nassar', N'Academic standing: Probation', N'Your cumulative GPA is 0.23. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'k.nassar', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'm.naccache2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'd.lteif', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.naccache', N'Academic standing: Probation', N'Your cumulative GPA is 0.66. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'f.naccache', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.diab2', N'Academic standing: Probation', N'Your cumulative GPA is 0.36. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'c.diab2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'c.chalhoub2', N'Academic standing: Probation', N'Your cumulative GPA is 0.71. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'c.chalhoub2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'f.abourjeily2', N'Academic standing: Probation', N'Your cumulative GPA is 0.09. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'f.abourjeily2', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'l.frangieh', N'Academic standing: Probation', N'Your cumulative GPA is 0.9. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'l.frangieh', N'Welcome back for Fall 2025', N'Registration is confirmed for the current semester. Check My Timetable for your schedule.', N'INFO', 1),
    (N'n.azzi', N'Academic standing: Probation', N'Your cumulative GPA is 1.1. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'g.moussawi2', N'Academic standing: Probation', N'Your cumulative GPA is 1.78. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'f.chalhoub', N'Academic standing: Probation', N'Your cumulative GPA is 1.16. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'g.sabbagh', N'Academic standing: Probation', N'Your cumulative GPA is 1.99. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'a.hamdan2', N'Academic standing: Probation', N'Your cumulative GPA is 1.63. You have been placed on academic probation and your maximum load is now 12 credits per semester.', N'WARNING', 0),
    (N'a.tabet', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'b.rahme', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'c.kanaan', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'd.fahed', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'd.hamdan', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'd.rahme', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'e.brown', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'e.chehab', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'e.chidiac', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'e.salloum', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'f.baaklini', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'f.chehab', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'f.davis', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'f.farah', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'f.smith2', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'g.choueiri', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'g.younes', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'h.assaf', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'h.chalhoub', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'h.doumit', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'h.issa', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'i.diab2', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'i.zoghbi', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'j.barakat2', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'j.doumit2', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'j.eid2', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'j.eid3', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'j.farah', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'j.kassem', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'j.mansour', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'k.doumit', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'k.younes', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'k.zoghbi', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'l.azzi', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'l.feghali', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'l.jaber', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'l.jureidini', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'm.chami', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'm.habib2', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'n.fares', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'n.tabet', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'o.aoun', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'o.bejjani2', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'o.saleh', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'p.habib', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'r.chalhoub2', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'r.jaber', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'r.lahoud', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'r.saad', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'r.wehbe', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'r.zoghbi3', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N's.choueiri', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N's.jaber', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N's.sleiman', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N't.jureidini', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N't.kassem', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'w.chalhoub', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'w.khalife', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'y.naccache', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N'z.rizk', N'Added to waiting list', N'You have been added to the waiting list for MATH101. We will notify you if a seat becomes available.', N'WAITLIST', 0),
    (N't.yazji', N'Grade posted for LAW213', N'Your grade for LAW213 has been posted: C+.', N'GRADE', 1),
    (N'd.chaaya', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: A-.', N'GRADE', 1),
    (N'w.deeb', N'Grade posted for LAW136', N'Your grade for LAW136 has been posted: B.', N'GRADE', 1),
    (N'f.abourjeily2', N'Grade posted for ENG346', N'Your grade for ENG346 has been posted: F.', N'GRADE', 1),
    (N'o.saad', N'Grade posted for MATH147', N'Your grade for MATH147 has been posted: B.', N'GRADE', 1),
    (N'c.diab2', N'Grade posted for LAW425', N'Your grade for LAW425 has been posted: F.', N'GRADE', 1),
    (N's.karam', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B+.', N'GRADE', 1),
    (N's.zoghbi', N'Grade posted for ARTS313', N'Your grade for ARTS313 has been posted: B.', N'GRADE', 1),
    (N't.chidiac2', N'Grade posted for MATH128', N'Your grade for MATH128 has been posted: C+.', N'GRADE', 1),
    (N'i.diab', N'Grade posted for ENG128', N'Your grade for ENG128 has been posted: A-.', N'GRADE', 1),
    (N'y.ibrahim', N'Grade posted for LAW213', N'Your grade for LAW213 has been posted: C+.', N'GRADE', 1),
    (N'j.barakat', N'Grade posted for MATH128', N'Your grade for MATH128 has been posted: C+.', N'GRADE', 1),
    (N't.matta2', N'Grade posted for ENG353', N'Your grade for ENG353 has been posted: B+.', N'GRADE', 1),
    (N'k.chalhoub', N'Grade posted for ARTS234', N'Your grade for ARTS234 has been posted: A.', N'GRADE', 1),
    (N'n.kanaan', N'Grade posted for ENG146', N'Your grade for ENG146 has been posted: F.', N'GRADE', 1),
    (N'c.diab', N'Grade posted for ENG138', N'Your grade for ENG138 has been posted: B+.', N'GRADE', 1),
    (N'c.baaklini', N'Grade posted for IT133', N'Your grade for IT133 has been posted: C.', N'GRADE', 1),
    (N'c.sleiman', N'Grade posted for CS115', N'Your grade for CS115 has been posted: C+.', N'GRADE', 1),
    (N'a.obeid', N'Grade posted for ARTS341', N'Your grade for ARTS341 has been posted: B-.', N'GRADE', 1),
    (N'k.wehbe2', N'Grade posted for ARTS335', N'Your grade for ARTS335 has been posted: B.', N'GRADE', 1),
    (N'r.daher', N'Grade posted for BUS128', N'Your grade for BUS128 has been posted: B-.', N'GRADE', 1),
    (N'a.naccache', N'Grade posted for BUS238', N'Your grade for BUS238 has been posted: A-.', N'GRADE', 1),
    (N's.chidiac', N'Grade posted for PHR343', N'Your grade for PHR343 has been posted: C.', N'GRADE', 1),
    (N'a.barakat', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B+.', N'GRADE', 1),
    (N'a.smith', N'Grade posted for PHR156', N'Your grade for PHR156 has been posted: B.', N'GRADE', 1),
    (N'k.gemayel', N'Grade posted for PHR111', N'Your grade for PHR111 has been posted: B-.', N'GRADE', 1),
    (N'b.obeid', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: A-.', N'GRADE', 1),
    (N'e.nakhoul', N'Grade posted for ARTS134', N'Your grade for ARTS134 has been posted: B.', N'GRADE', 1),
    (N'c.tabet', N'Grade posted for ARTS123', N'Your grade for ARTS123 has been posted: B.', N'GRADE', 1),
    (N't.abourjeily', N'Grade posted for PHR241', N'Your grade for PHR241 has been posted: B+.', N'GRADE', 1),
    (N'k.boutros', N'Grade posted for LAW251', N'Your grade for LAW251 has been posted: B.', N'GRADE', 1),
    (N'r.tabet', N'Grade posted for BUS211', N'Your grade for BUS211 has been posted: B.', N'GRADE', 1),
    (N'f.saad', N'Grade posted for ENG222', N'Your grade for ENG222 has been posted: B+.', N'GRADE', 1),
    (N'z.obeid', N'Grade posted for ENG222', N'Your grade for ENG222 has been posted: B+.', N'GRADE', 1),
    (N'l.issa', N'Grade posted for MATH117', N'Your grade for MATH117 has been posted: A-.', N'GRADE', 1),
    (N's.fahed', N'Grade posted for CS202', N'Your grade for CS202 has been posted: A.', N'GRADE', 1),
    (N'n.obeid', N'Grade posted for MATH147', N'Your grade for MATH147 has been posted: B.', N'GRADE', 1),
    (N'k.chalhoub', N'Grade posted for ARTS217', N'Your grade for ARTS217 has been posted: B+.', N'GRADE', 1),
    (N'k.chalhoub', N'Grade posted for ARTS152', N'Your grade for ARTS152 has been posted: B.', N'GRADE', 1),
    (N'a.miller', N'Grade posted for ENG222', N'Your grade for ENG222 has been posted: C+.', N'GRADE', 1),
    (N't.baaklini', N'Grade posted for LAW331', N'Your grade for LAW331 has been posted: A-.', N'GRADE', 1),
    (N'n.williams', N'Grade posted for ENG217', N'Your grade for ENG217 has been posted: B.', N'GRADE', 1),
    (N'm.maalouf', N'Grade posted for MATH413', N'Your grade for MATH413 has been posted: B-.', N'GRADE', 1),
    (N'd.karam', N'Grade posted for ENG353', N'Your grade for ENG353 has been posted: B-.', N'GRADE', 1),
    (N'p.osman', N'Grade posted for IT328', N'Your grade for IT328 has been posted: B.', N'GRADE', 1),
    (N'm.naccache2', N'Grade posted for PHR135', N'Your grade for PHR135 has been posted: F.', N'GRADE', 1),
    (N'b.obeid', N'Grade posted for LAW145', N'Your grade for LAW145 has been posted: A-.', N'GRADE', 1),
    (N'c.kassem', N'Grade posted for ENG252', N'Your grade for ENG252 has been posted: C+.', N'GRADE', 1),
    (N'm.geagea', N'Grade posted for ENG156', N'Your grade for ENG156 has been posted: B+.', N'GRADE', 1),
    (N'g.obeid', N'Grade posted for ENG128', N'Your grade for ENG128 has been posted: B.', N'GRADE', 1),
    (N'f.issa', N'Grade posted for CS115', N'Your grade for CS115 has been posted: B.', N'GRADE', 1),
    (N'j.lteif', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: A-.', N'GRADE', 1),
    (N'a.fares', N'Grade posted for ENG118', N'Your grade for ENG118 has been posted: A-.', N'GRADE', 1),
    (N's.chidiac', N'Grade posted for PHR213', N'Your grade for PHR213 has been posted: C+.', N'GRADE', 1),
    (N'd.lahoud', N'Grade posted for ENG312', N'Your grade for ENG312 has been posted: C+.', N'GRADE', 1),
    (N'a.chami2', N'Grade posted for ARTS152', N'Your grade for ARTS152 has been posted: C+.', N'GRADE', 1),
    (N't.baaklini2', N'Grade posted for PHR124', N'Your grade for PHR124 has been posted: D+.', N'GRADE', 1),
    (N'a.rizk', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: F.', N'GRADE', 1),
    (N'a.smith', N'Grade posted for PHR315', N'Your grade for PHR315 has been posted: B.', N'GRADE', 1),
    (N'h.sleiman', N'Grade posted for ENG118', N'Your grade for ENG118 has been posted: B.', N'GRADE', 1),
    (N'g.moussawi2', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: C-.', N'GRADE', 1),
    (N'k.wehbe2', N'Grade posted for ARTS123', N'Your grade for ARTS123 has been posted: B.', N'GRADE', 1),
    (N'r.yazbek', N'Grade posted for ENG326', N'Your grade for ENG326 has been posted: A-.', N'GRADE', 1),
    (N't.chalhoub', N'Grade posted for ENG156', N'Your grade for ENG156 has been posted: B+.', N'GRADE', 1),
    (N'b.yazji', N'Grade posted for PHR135', N'Your grade for PHR135 has been posted: B.', N'GRADE', 1),
    (N'k.nasr', N'Grade posted for LAW245', N'Your grade for LAW245 has been posted: B-.', N'GRADE', 1),
    (N'k.boutros', N'Grade posted for LAW231', N'Your grade for LAW231 has been posted: B+.', N'GRADE', 1),
    (N'e.hamdan', N'Grade posted for ENG138', N'Your grade for ENG138 has been posted: B+.', N'GRADE', 1),
    (N'r.farah', N'Grade posted for CS148', N'Your grade for CS148 has been posted: F.', N'GRADE', 1),
    (N'c.kassem', N'Grade posted for ENG245', N'Your grade for ENG245 has been posted: C+.', N'GRADE', 1),
    (N'n.wehbe', N'Grade posted for PHR233', N'Your grade for PHR233 has been posted: B+.', N'GRADE', 1),
    (N'd.jaber', N'Grade posted for CS128', N'Your grade for CS128 has been posted: A-.', N'GRADE', 1),
    (N'i.deeb', N'Grade posted for CS115', N'Your grade for CS115 has been posted: B+.', N'GRADE', 1),
    (N'j.doumit', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: F.', N'GRADE', 1),
    (N'c.rahal', N'Grade posted for CS134', N'Your grade for CS134 has been posted: B+.', N'GRADE', 1),
    (N'h.lahoud', N'Grade posted for CS101', N'Your grade for CS101 has been posted: B-.', N'GRADE', 1),
    (N'a.fares', N'Grade posted for ENG156', N'Your grade for ENG156 has been posted: B+.', N'GRADE', 1),
    (N'n.johnson', N'Grade posted for CS248', N'Your grade for CS248 has been posted: B-.', N'GRADE', 1),
    (N'n.obeid', N'Grade posted for MATH316', N'Your grade for MATH316 has been posted: B+.', N'GRADE', 1),
    (N'k.nasr', N'Grade posted for LAW128', N'Your grade for LAW128 has been posted: C+.', N'GRADE', 1),
    (N's.salloum', N'Grade posted for ENG156', N'Your grade for ENG156 has been posted: B+.', N'GRADE', 1),
    (N'm.lahoud', N'Grade posted for MATH158', N'Your grade for MATH158 has been posted: B.', N'GRADE', 1),
    (N'm.naccache2', N'Grade posted for PHR353', N'Your grade for PHR353 has been posted: F.', N'GRADE', 1),
    (N'm.naccache', N'Grade posted for ENG238', N'Your grade for ENG238 has been posted: B.', N'GRADE', 1),
    (N'd.lteif', N'Grade posted for LAW326', N'Your grade for LAW326 has been posted: F.', N'GRADE', 1),
    (N'k.habib', N'Grade posted for MATH334', N'Your grade for MATH334 has been posted: A-.', N'GRADE', 1),
    (N'm.naccache2', N'Grade posted for PHR343', N'Your grade for PHR343 has been posted: F.', N'GRADE', 1),
    (N'e.moussawi', N'Grade posted for LAW251', N'Your grade for LAW251 has been posted: F.', N'GRADE', 1),
    (N'k.nasr', N'Grade posted for LAW145', N'Your grade for LAW145 has been posted: C+.', N'GRADE', 1),
    (N'h.jureidini', N'Grade posted for ARTS313', N'Your grade for ARTS313 has been posted: B+.', N'GRADE', 1),
    (N'h.gemayel', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B.', N'GRADE', 1),
    (N'a.chami', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B.', N'GRADE', 1),
    (N'n.chaaya', N'Grade posted for ARTS217', N'Your grade for ARTS217 has been posted: F.', N'GRADE', 1),
    (N'a.obeid', N'Grade posted for ARTS432', N'Your grade for ARTS432 has been posted: C+.', N'GRADE', 1),
    (N'd.chami', N'Grade posted for ENG138', N'Your grade for ENG138 has been posted: B-.', N'GRADE', 1),
    (N'h.aoun', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B.', N'GRADE', 1),
    (N'l.doumit', N'Grade posted for IT153', N'Your grade for IT153 has been posted: A-.', N'GRADE', 1),
    (N'w.fahed', N'Grade posted for BUS253', N'Your grade for BUS253 has been posted: C+.', N'GRADE', 1),
    (N'j.eid', N'Grade posted for ARTS134', N'Your grade for ARTS134 has been posted: C.', N'GRADE', 1),
    (N'z.ghosn', N'Grade posted for MATH117', N'Your grade for MATH117 has been posted: D.', N'GRADE', 1),
    (N'h.eid', N'Grade posted for IT228', N'Your grade for IT228 has been posted: B+.', N'GRADE', 1),
    (N'r.farah', N'Grade posted for CS248', N'Your grade for CS248 has been posted: F.', N'GRADE', 1),
    (N'f.lahoud', N'Grade posted for CS148', N'Your grade for CS148 has been posted: A.', N'GRADE', 1),
    (N'y.brown', N'Grade posted for MATH243', N'Your grade for MATH243 has been posted: B-.', N'GRADE', 1),
    (N'g.sabbagh', N'Grade posted for ENG118', N'Your grade for ENG118 has been posted: C-.', N'GRADE', 1),
    (N'f.rahal', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B-.', N'GRADE', 1),
    (N'a.rizk', N'Grade posted for IT228', N'Your grade for IT228 has been posted: F.', N'GRADE', 1),
    (N's.salloum', N'Grade posted for ENG118', N'Your grade for ENG118 has been posted: B.', N'GRADE', 1),
    (N'i.rahme2', N'Grade posted for MATH258', N'Your grade for MATH258 has been posted: C+.', N'GRADE', 1),
    (N'm.geagea', N'Grade posted for ENG138', N'Your grade for ENG138 has been posted: B+.', N'GRADE', 1),
    (N'g.salloum', N'Grade posted for BUS238', N'Your grade for BUS238 has been posted: B.', N'GRADE', 1),
    (N'o.saleh', N'Grade posted for CS101', N'Your grade for CS101 has been posted: F.', N'GRADE', 1),
    (N'i.lahoud', N'Grade posted for ENG326', N'Your grade for ENG326 has been posted: C+.', N'GRADE', 1),
    (N'd.jaber', N'Grade posted for CS148', N'Your grade for CS148 has been posted: A-.', N'GRADE', 1),
    (N'h.sleiman', N'Grade posted for ENG426', N'Your grade for ENG426 has been posted: B.', N'GRADE', 1),
    (N'n.johnson', N'Grade posted for CS202', N'Your grade for CS202 has been posted: C+.', N'GRADE', 1),
    (N'a.azzi', N'Grade posted for ARTS152', N'Your grade for ARTS152 has been posted: B+.', N'GRADE', 1),
    (N't.matta2', N'Grade posted for ENG338', N'Your grade for ENG338 has been posted: B+.', N'GRADE', 1),
    (N'h.aoun', N'Grade posted for BUS128', N'Your grade for BUS128 has been posted: B.', N'GRADE', 1),
    (N't.abourjeily', N'Grade posted for PHR142', N'Your grade for PHR142 has been posted: A-.', N'GRADE', 1),
    (N'c.lteif', N'Grade posted for ENG252', N'Your grade for ENG252 has been posted: C.', N'GRADE', 1),
    (N'k.habib', N'Grade posted for MATH216', N'Your grade for MATH216 has been posted: A-.', N'GRADE', 1),
    (N'm.obeid', N'Grade posted for ENG326', N'Your grade for ENG326 has been posted: C+.', N'GRADE', 1),
    (N'j.maalouf', N'Grade posted for ARTS152', N'Your grade for ARTS152 has been posted: B-.', N'GRADE', 1),
    (N'd.karam', N'Grade posted for ENG128', N'Your grade for ENG128 has been posted: B-.', N'GRADE', 1),
    (N'h.sfeir', N'Grade posted for ENG312', N'Your grade for ENG312 has been posted: B+.', N'GRADE', 1),
    (N'n.assaf', N'Grade posted for ENG312', N'Your grade for ENG312 has been posted: B.', N'GRADE', 1),
    (N'm.maalouf', N'Grade posted for MATH227', N'Your grade for MATH227 has been posted: B-.', N'GRADE', 1),
    (N'h.eid', N'Grade posted for IT238', N'Your grade for IT238 has been posted: A-.', N'GRADE', 1),
    (N'g.sfeir', N'Grade posted for CS217', N'Your grade for CS217 has been posted: A-.', N'GRADE', 1),
    (N't.baaklini', N'Grade posted for LAW314', N'Your grade for LAW314 has been posted: B+.', N'GRADE', 1),
    (N'g.geagea', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: A-.', N'GRADE', 1),
    (N'l.issa', N'Grade posted for MATH227', N'Your grade for MATH227 has been posted: A-.', N'GRADE', 1),
    (N'n.johnson', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B-.', N'GRADE', 1),
    (N'c.yazji', N'Grade posted for ARTS217', N'Your grade for ARTS217 has been posted: C+.', N'GRADE', 1),
    (N'f.naccache', N'Grade posted for IT358', N'Your grade for IT358 has been posted: D.', N'GRADE', 1),
    (N't.baaklini', N'Grade posted for LAW155', N'Your grade for LAW155 has been posted: B+.', N'GRADE', 1),
    (N'l.davis', N'Grade posted for CS101', N'Your grade for CS101 has been posted: B.', N'GRADE', 1),
    (N'w.davis', N'Grade posted for MATH128', N'Your grade for MATH128 has been posted: F.', N'GRADE', 1),
    (N'n.farah', N'Grade posted for ARTS234', N'Your grade for ARTS234 has been posted: B.', N'GRADE', 1),
    (N'a.miller', N'Grade posted for ENG238', N'Your grade for ENG238 has been posted: B.', N'GRADE', 1),
    (N'z.obeid', N'Grade posted for ENG346', N'Your grade for ENG346 has been posted: B+.', N'GRADE', 1),
    (N'f.maalouf2', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B-.', N'GRADE', 1),
    (N'y.khalife', N'Grade posted for PHR343', N'Your grade for PHR343 has been posted: B.', N'GRADE', 1),
    (N'w.fahed', N'Grade posted for BUS332', N'Your grade for BUS332 has been posted: C.', N'GRADE', 1),
    (N'n.chalhoub', N'Grade posted for ENG217', N'Your grade for ENG217 has been posted: A.', N'GRADE', 1),
    (N'y.chami', N'Grade posted for PHR124', N'Your grade for PHR124 has been posted: B.', N'GRADE', 1),
    (N'd.choueiri', N'Grade posted for MATH352', N'Your grade for MATH352 has been posted: A.', N'GRADE', 1),
    (N'c.rahal', N'Grade posted for CS128', N'Your grade for CS128 has been posted: B.', N'GRADE', 1),
    (N't.chidiac2', N'Grade posted for MATH131', N'Your grade for MATH131 has been posted: B.', N'GRADE', 1),
    (N'f.younes', N'Grade posted for ENG426', N'Your grade for ENG426 has been posted: B+.', N'GRADE', 1),
    (N'n.karam', N'Grade posted for CS202', N'Your grade for CS202 has been posted: B.', N'GRADE', 1),
    (N'g.ghosn', N'Grade posted for PHR213', N'Your grade for PHR213 has been posted: F.', N'GRADE', 1),
    (N'm.feghali', N'Grade posted for ENG222', N'Your grade for ENG222 has been posted: D.', N'GRADE', 1),
    (N'g.chaaya', N'Grade posted for ARTS323', N'Your grade for ARTS323 has been posted: B+.', N'GRADE', 1),
    (N'n.wehbe', N'Grade posted for PHR124', N'Your grade for PHR124 has been posted: B.', N'GRADE', 1),
    (N'n.wehbe', N'Grade posted for PHR327', N'Your grade for PHR327 has been posted: B.', N'GRADE', 1),
    (N'a.feghali', N'Grade posted for LAW341', N'Your grade for LAW341 has been posted: B+.', N'GRADE', 1),
    (N'k.gemayel', N'Grade posted for PHR142', N'Your grade for PHR142 has been posted: B-.', N'GRADE', 1),
    (N'm.habib', N'Grade posted for ENG238', N'Your grade for ENG238 has been posted: B+.', N'GRADE', 1),
    (N'f.issa', N'Grade posted for CS248', N'Your grade for CS248 has been posted: A-.', N'GRADE', 1),
    (N'a.hamdan', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B+.', N'GRADE', 1),
    (N'd.karam', N'Grade posted for ENG217', N'Your grade for ENG217 has been posted: B-.', N'GRADE', 1),
    (N's.chidiac2', N'Grade posted for BUS222', N'Your grade for BUS222 has been posted: B-.', N'GRADE', 1),
    (N'o.bejjani', N'Grade posted for LAW145', N'Your grade for LAW145 has been posted: B-.', N'GRADE', 1),
    (N's.chidiac3', N'Grade posted for BUS136', N'Your grade for BUS136 has been posted: B.', N'GRADE', 1),
    (N'k.nasr', N'Grade posted for LAW251', N'Your grade for LAW251 has been posted: B-.', N'GRADE', 1),
    (N'z.obeid', N'Grade posted for ENG118', N'Your grade for ENG118 has been posted: B+.', N'GRADE', 1),
    (N'g.sabbagh', N'Grade posted for ENG128', N'Your grade for ENG128 has been posted: C.', N'GRADE', 1),
    (N'm.frangieh', N'Grade posted for ENG238', N'Your grade for ENG238 has been posted: B.', N'GRADE', 1),
    (N'f.issa', N'Grade posted for CS317', N'Your grade for CS317 has been posted: B+.', N'GRADE', 1),
    (N't.kassem2', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: D.', N'GRADE', 1),
    (N'r.osman', N'Grade posted for PHR156', N'Your grade for PHR156 has been posted: C+.', N'GRADE', 1),
    (N'c.chalhoub2', N'Grade posted for BUS112', N'Your grade for BUS112 has been posted: D+.', N'GRADE', 1),
    (N'a.abourjeily', N'Grade posted for MATH128', N'Your grade for MATH128 has been posted: B-.', N'GRADE', 1),
    (N'f.karkafi', N'Grade posted for LAW118', N'Your grade for LAW118 has been posted: B.', N'GRADE', 1),
    (N'a.feghali', N'Grade posted for LAW354', N'Your grade for LAW354 has been posted: B+.', N'GRADE', 1),
    (N'j.smith', N'Grade posted for BUS426', N'Your grade for BUS426 has been posted: B.', N'GRADE', 1),
    (N'y.ibrahim', N'Grade posted for LAW128', N'Your grade for LAW128 has been posted: B.', N'GRADE', 1),
    (N'r.yazbek', N'Grade posted for ENG353', N'Your grade for ENG353 has been posted: B.', N'GRADE', 1),
    (N'o.saad', N'Grade posted for MATH243', N'Your grade for MATH243 has been posted: A-.', N'GRADE', 1),
    (N'd.sleiman', N'Grade posted for CS166', N'Your grade for CS166 has been posted: C+.', N'GRADE', 1),
    (N't.chalhoub', N'Grade posted for ENG222', N'Your grade for ENG222 has been posted: A.', N'GRADE', 1),
    (N'g.geagea', N'Grade posted for PHR241', N'Your grade for PHR241 has been posted: B+.', N'GRADE', 1),
    (N'n.choueiri', N'Grade posted for MATH227', N'Your grade for MATH227 has been posted: B+.', N'GRADE', 1),
    (N'l.zeidan', N'Grade posted for PHR156', N'Your grade for PHR156 has been posted: A-.', N'GRADE', 1),
    (N'a.azzi', N'Grade posted for ARTS123', N'Your grade for ARTS123 has been posted: B.', N'GRADE', 1),
    (N'c.diab', N'Grade posted for ENG118', N'Your grade for ENG118 has been posted: A-.', N'GRADE', 1),
    (N't.kassem2', N'Grade posted for IT254', N'Your grade for IT254 has been posted: D+.', N'GRADE', 1),
    (N'c.chami', N'Grade posted for MATH243', N'Your grade for MATH243 has been posted: B+.', N'GRADE', 1),
    (N'k.wehbe', N'Grade posted for ENG138', N'Your grade for ENG138 has been posted: B+.', N'GRADE', 1),
    (N'f.lahoud', N'Grade posted for CS251', N'Your grade for CS251 has been posted: A-.', N'GRADE', 1),
    (N't.raad', N'Grade posted for IT124', N'Your grade for IT124 has been posted: B.', N'GRADE', 1),
    (N'l.farah', N'Grade posted for ENG217', N'Your grade for ENG217 has been posted: B-.', N'GRADE', 1),
    (N'c.chalhoub2', N'Grade posted for BUS437', N'Your grade for BUS437 has been posted: F.', N'GRADE', 1),
    (N'k.gemayel', N'Grade posted for PHR156', N'Your grade for PHR156 has been posted: B.', N'GRADE', 1),
    (N'd.frangieh', N'Grade posted for ARTS117', N'Your grade for ARTS117 has been posted: A-.', N'GRADE', 1),
    (N'm.obeid', N'Grade posted for ENG426', N'Your grade for ENG426 has been posted: B.', N'GRADE', 1),
    (N'y.chaaya', N'Grade posted for ARTS123', N'Your grade for ARTS123 has been posted: A-.', N'GRADE', 1),
    (N'f.issa', N'Grade posted for CS267', N'Your grade for CS267 has been posted: B+.', N'GRADE', 1),
    (N'c.lteif', N'Grade posted for ENG312', N'Your grade for ENG312 has been posted: C+.', N'GRADE', 1),
    (N't.abourjeily', N'Grade posted for PHR315', N'Your grade for PHR315 has been posted: B.', N'GRADE', 1),
    (N'h.eid', N'Grade posted for IT211', N'Your grade for IT211 has been posted: A-.', N'GRADE', 1),
    (N'l.chalhoub', N'Grade posted for PHR223', N'Your grade for PHR223 has been posted: F.', N'GRADE', 1),
    (N'm.sabbagh', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B-.', N'GRADE', 1),
    (N'f.saad', N'Grade posted for ENG238', N'Your grade for ENG238 has been posted: B+.', N'GRADE', 1),
    (N'g.obeid', N'Grade posted for ENG146', N'Your grade for ENG146 has been posted: B-.', N'GRADE', 1),
    (N'n.obeid', N'Grade posted for MATH243', N'Your grade for MATH243 has been posted: B+.', N'GRADE', 1),
    (N'n.karam', N'Grade posted for CS436', N'Your grade for CS436 has been posted: B-.', N'GRADE', 1),
    (N'i.deeb', N'Grade posted for CS134', N'Your grade for CS134 has been posted: B.', N'GRADE', 1),
    (N'j.chalhoub', N'Grade posted for ENG217', N'Your grade for ENG217 has been posted: C+.', N'GRADE', 1),
    (N'm.baaklini', N'Grade posted for IT144', N'Your grade for IT144 has been posted: A-.', N'GRADE', 1),
    (N'c.baaklini', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B-.', N'GRADE', 1),
    (N's.zoghbi', N'Grade posted for ARTS225', N'Your grade for ARTS225 has been posted: B.', N'GRADE', 1),
    (N't.baaklini2', N'Grade posted for PHR223', N'Your grade for PHR223 has been posted: D.', N'GRADE', 1),
    (N'r.tabet', N'Grade posted for BUS112', N'Your grade for BUS112 has been posted: B-.', N'GRADE', 1),
    (N'g.sfeir', N'Grade posted for CS101', N'Your grade for CS101 has been posted: A-.', N'GRADE', 1),
    (N't.kassem2', N'Grade posted for IT358', N'Your grade for IT358 has been posted: D.', N'GRADE', 1),
    (N'g.sabbagh', N'Grade posted for ENG217', N'Your grade for ENG217 has been posted: C.', N'GRADE', 1),
    (N'j.chalhoub', N'Grade posted for ENG128', N'Your grade for ENG128 has been posted: C+.', N'GRADE', 1),
    (N'n.obeid', N'Grade posted for MATH327', N'Your grade for MATH327 has been posted: B-.', N'GRADE', 1),
    (N's.salloum', N'Grade posted for ENG238', N'Your grade for ENG238 has been posted: A-.', N'GRADE', 1),
    (N'o.khalife', N'Grade posted for ENG217', N'Your grade for ENG217 has been posted: B.', N'GRADE', 1),
    (N'c.yazji', N'Grade posted for ARTS117', N'Your grade for ARTS117 has been posted: F.', N'GRADE', 1),
    (N'l.frangieh', N'Grade posted for IT124', N'Your grade for IT124 has been posted: D+.', N'GRADE', 1),
    (N'g.bejjani', N'Grade posted for PHR135', N'Your grade for PHR135 has been posted: B+.', N'GRADE', 1),
    (N'y.khalife', N'Grade posted for PHR333', N'Your grade for PHR333 has been posted: B.', N'GRADE', 1),
    (N'f.ghosn3', N'Grade posted for CS202', N'Your grade for CS202 has been posted: B-.', N'GRADE', 1),
    (N'c.baaklini2', N'Grade posted for LAW118', N'Your grade for LAW118 has been posted: B.', N'GRADE', 1),
    (N'c.hobeika', N'Grade posted for PHR241', N'Your grade for PHR241 has been posted: B.', N'GRADE', 1),
    (N'g.sfeir', N'Grade posted for CS367', N'Your grade for CS367 has been posted: B+.', N'GRADE', 1),
    (N'a.hamdan', N'Grade posted for LAW222', N'Your grade for LAW222 has been posted: B+.', N'GRADE', 1),
    (N'a.abourjeily', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B+.', N'GRADE', 1),
    (N'h.gemayel', N'Grade posted for ENG245', N'Your grade for ENG245 has been posted: B+.', N'GRADE', 1),
    (N'c.chalhoub', N'Grade posted for ENG217', N'Your grade for ENG217 has been posted: B.', N'GRADE', 1),
    (N'b.azzi', N'Grade posted for IT241', N'Your grade for IT241 has been posted: B-.', N'GRADE', 1),
    (N'j.doumit', N'Grade posted for ENG245', N'Your grade for ENG245 has been posted: A.', N'GRADE', 1),
    (N'n.johnson', N'Grade posted for CS267', N'Your grade for CS267 has been posted: B.', N'GRADE', 1),
    (N'f.jaber', N'Grade posted for IT347', N'Your grade for IT347 has been posted: B+.', N'GRADE', 1),
    (N'j.doumit', N'Grade posted for ENG138', N'Your grade for ENG138 has been posted: A-.', N'GRADE', 1),
    (N'y.chami', N'Grade posted for PHR333', N'Your grade for PHR333 has been posted: B.', N'GRADE', 1),
    (N'n.kanaan', N'Grade posted for ENG353', N'Your grade for ENG353 has been posted: F.', N'GRADE', 1),
    (N'c.chalhoub2', N'Grade posted for BUS314', N'Your grade for BUS314 has been posted: F.', N'GRADE', 1),
    (N'r.daher2', N'Grade posted for MATH227', N'Your grade for MATH227 has been posted: C+.', N'GRADE', 1),
    (N'g.obeid', N'Grade posted for ENG252', N'Your grade for ENG252 has been posted: B.', N'GRADE', 1),
    (N'm.maalouf', N'Grade posted for MATH352', N'Your grade for MATH352 has been posted: B-.', N'GRADE', 1),
    (N'd.sleiman', N'Grade posted for CS237', N'Your grade for CS237 has been posted: C+.', N'GRADE', 1),
    (N'n.wehbe', N'Grade posted for PHR213', N'Your grade for PHR213 has been posted: B.', N'GRADE', 1),
    (N'c.kassem', N'Grade posted for ENG326', N'Your grade for ENG326 has been posted: B-.', N'GRADE', 1),
    (N'r.osman', N'Grade posted for PHR111', N'Your grade for PHR111 has been posted: C+.', N'GRADE', 1),
    (N't.matta2', N'Grade posted for ENG156', N'Your grade for ENG156 has been posted: B+.', N'GRADE', 1),
    (N'm.karkafi', N'Grade posted for MATH158', N'Your grade for MATH158 has been posted: B+.', N'GRADE', 1),
    (N's.fahed', N'Grade posted for CS102', N'Your grade for CS102 has been posted: A-.', N'GRADE', 1),
    (N'y.ibrahim', N'Grade posted for LAW145', N'Your grade for LAW145 has been posted: B-.', N'GRADE', 1),
    (N'd.nasr', N'Grade posted for ENG118', N'Your grade for ENG118 has been posted: B.', N'GRADE', 1),
    (N'n.wehbe', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B.', N'GRADE', 1),
    (N'n.gemayel', N'Grade posted for ENG128', N'Your grade for ENG128 has been posted: C-.', N'GRADE', 1),
    (N'k.raad', N'Grade posted for ARTS246', N'Your grade for ARTS246 has been posted: A-.', N'GRADE', 1),
    (N'r.brown', N'Grade posted for MATH316', N'Your grade for MATH316 has been posted: B.', N'GRADE', 1),
    (N't.yazji', N'Grade posted for LAW231', N'Your grade for LAW231 has been posted: C.', N'GRADE', 1),
    (N'b.azzi', N'Grade posted for IT114', N'Your grade for IT114 has been posted: C+.', N'GRADE', 1),
    (N'g.chaaya', N'Grade posted for ARTS341', N'Your grade for ARTS341 has been posted: A.', N'GRADE', 1),
    (N's.rahme', N'Grade posted for ENG217', N'Your grade for ENG217 has been posted: B-.', N'GRADE', 1),
    (N'd.sleiman', N'Grade posted for CS101', N'Your grade for CS101 has been posted: B-.', N'GRADE', 1),
    (N'e.hamdan', N'Grade posted for ENG146', N'Your grade for ENG146 has been posted: B+.', N'GRADE', 1),
    (N'b.azzi', N'Grade posted for IT124', N'Your grade for IT124 has been posted: B-.', N'GRADE', 1),
    (N'c.lteif', N'Grade posted for ENG156', N'Your grade for ENG156 has been posted: C+.', N'GRADE', 1),
    (N'c.rahal', N'Grade posted for CS201', N'Your grade for CS201 has been posted: B.', N'GRADE', 1),
    (N'm.naccache', N'Grade posted for ENG326', N'Your grade for ENG326 has been posted: B-.', N'GRADE', 1),
    (N'l.davis', N'Grade posted for CS251', N'Your grade for CS251 has been posted: B+.', N'GRADE', 1),
    (N'd.chaaya', N'Grade posted for IT133', N'Your grade for IT133 has been posted: B+.', N'GRADE', 1),
    (N'j.zeidan', N'Grade posted for IT124', N'Your grade for IT124 has been posted: D+.', N'GRADE', 1),
    (N'y.miller', N'Grade posted for MATH347', N'Your grade for MATH347 has been posted: B-.', N'GRADE', 1),
    (N'c.diab', N'Grade posted for ENG156', N'Your grade for ENG156 has been posted: B.', N'GRADE', 1),
    (N's.rahme', N'Grade posted for ENG156', N'Your grade for ENG156 has been posted: C+.', N'GRADE', 1),
    (N'e.hamdan', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: B+.', N'GRADE', 1),
    (N't.abourjeily', N'Grade posted for PHR327', N'Your grade for PHR327 has been posted: B+.', N'GRADE', 1),
    (N'h.eid', N'Grade posted for IT333', N'Your grade for IT333 has been posted: A-.', N'GRADE', 1),
    (N'l.fahed', N'Grade posted for ARTS134', N'Your grade for ARTS134 has been posted: B-.', N'GRADE', 1),
    (N'l.barakat', N'Grade posted for ENG118', N'Your grade for ENG118 has been posted: B+.', N'GRADE', 1),
    (N'k.moussawi', N'Grade posted for CS102', N'Your grade for CS102 has been posted: A-.', N'GRADE', 1),
    (N'k.mansour', N'Grade posted for BUS332', N'Your grade for BUS332 has been posted: C+.', N'GRADE', 1),
    (N'f.rahal', N'Grade posted for LAW213', N'Your grade for LAW213 has been posted: B+.', N'GRADE', 1),
    (N'k.rizk', N'Grade posted for BUS128', N'Your grade for BUS128 has been posted: B+.', N'GRADE', 1),
    (N'l.davis', N'Grade posted for CS102', N'Your grade for CS102 has been posted: A-.', N'GRADE', 1),
    (N'l.frangieh', N'Grade posted for IT144', N'Your grade for IT144 has been posted: F.', N'GRADE', 1),
    (N'f.rahal', N'Grade posted for LAW331', N'Your grade for LAW331 has been posted: B.', N'GRADE', 1),
    (N'j.baaklini', N'Grade posted for ARTS217', N'Your grade for ARTS217 has been posted: B.', N'GRADE', 1),
    (N'g.chaaya', N'Grade posted for ARTS123', N'Your grade for ARTS123 has been posted: B+.', N'GRADE', 1),
    (N'n.johnson', N'Grade posted for CS134', N'Your grade for CS134 has been posted: C+.', N'GRADE', 1),
    (N'l.nasr', N'Grade posted for ENG238', N'Your grade for ENG238 has been posted: B.', N'GRADE', 1),
    (N'l.boutros', N'Grade posted for IT328', N'Your grade for IT328 has been posted: A-.', N'GRADE', 1),
    (N'a.diab', N'Grade posted for LAW118', N'Your grade for LAW118 has been posted: C+.', N'GRADE', 1),
    (N'm.karkafi', N'Grade posted for MATH352', N'Your grade for MATH352 has been posted: B.', N'GRADE', 1),
    (N'n.habib', N'Grade posted for ARTS341', N'Your grade for ARTS341 has been posted: C+.', N'GRADE', 1),
    (N'n.boutros', N'Grade posted for ENG252', N'Your grade for ENG252 has been posted: B-.', N'GRADE', 1),
    (N'i.geagea', N'Grade posted for ENG118', N'Your grade for ENG118 has been posted: F.', N'GRADE', 1),
    (N'h.sleiman', N'Grade posted for ENG238', N'Your grade for ENG238 has been posted: B-.', N'GRADE', 1),
    (N'm.eid', N'Grade posted for MATH243', N'Your grade for MATH243 has been posted: F.', N'GRADE', 1),
    (N'k.boutros', N'Grade posted for LAW245', N'Your grade for LAW245 has been posted: B-.', N'GRADE', 1),
    (N'm.chaaya', N'Grade posted for CS148', N'Your grade for CS148 has been posted: B.', N'GRADE', 1),
    (N'd.choueiri', N'Grade posted for MATH158', N'Your grade for MATH158 has been posted: B+.', N'GRADE', 1),
    (N'a.fares', N'Grade posted for ENG338', N'Your grade for ENG338 has been posted: B+.', N'GRADE', 1),
    (N'j.eid', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: C.', N'GRADE', 1),
    (N'g.geagea', N'Grade posted for PHR353', N'Your grade for PHR353 has been posted: B+.', N'GRADE', 1),
    (N'w.gemayel', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: F.', N'GRADE', 1),
    (N'k.moussawi', N'Grade posted for CS367', N'Your grade for CS367 has been posted: A.', N'GRADE', 1),
    (N'd.yazbek', N'Grade posted for LAW136', N'Your grade for LAW136 has been posted: B+.', N'GRADE', 1),
    (N'j.lteif', N'Grade posted for BUS128', N'Your grade for BUS128 has been posted: A-.', N'GRADE', 1),
    (N'm.lahoud', N'Grade posted for MATH128', N'Your grade for MATH128 has been posted: B-.', N'GRADE', 1),
    (N'n.choueiri', N'Grade posted for MATH233', N'Your grade for MATH233 has been posted: A-.', N'GRADE', 1),
    (N'c.chami', N'Grade posted for MATH233', N'Your grade for MATH233 has been posted: B-.', N'GRADE', 1),
    (N'g.bejjani', N'Grade posted for PHR213', N'Your grade for PHR213 has been posted: B+.', N'GRADE', 1),
    (N'n.geagea', N'Grade posted for ARTS123', N'Your grade for ARTS123 has been posted: C.', N'GRADE', 1),
    (N'n.davis', N'Grade posted for MATH431', N'Your grade for MATH431 has been posted: B+.', N'GRADE', 1),
    (N'i.deeb', N'Grade posted for CS201', N'Your grade for CS201 has been posted: B+.', N'GRADE', 1),
    (N'm.lahoud', N'Grade posted for MATH101', N'Your grade for MATH101 has been posted: A-.', N'GRADE', 1),
    (N'i.rahme', N'Grade posted for ENG156', N'Your grade for ENG156 has been posted: C.', N'GRADE', 1),
    (N'n.karam', N'Grade posted for CS317', N'Your grade for CS317 has been posted: B.', N'GRADE', 1),
    (N'a.lteif', N'Grade posted for CS166', N'Your grade for CS166 has been posted: C.', N'GRADE', 1)
) AS v(username, title, msg, ntype, isread)
JOIN dbo.users u ON u.username = v.username;

COMMIT TRANSACTION;
PRINT N'>>> SEED 09 (notifications) completed.';
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    PRINT N'!!! SEED 09 (notifications) FAILED, rolled back: ' + ERROR_MESSAGE();
    THROW;
END CATCH
GO
