package com.university.service;

import com.university.dao.AbstractDAO;
import com.university.dao.DepartmentDAO;
import com.university.dao.InstructorDAO;
import com.university.dao.UserDAO;
import com.university.enums.UserRole;
import com.university.model.Instructor;
import com.university.util.ValidationUtil;

import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;

/**
 * Everything the admin does to instructor records.
 *
 * <p>Mirrors {@link StudentService} in every structural way. An instructor's
 * identity is {@code users.user_id}, shown as the <b>Instructor ID</b> and
 * generated by SQL Server; creating one writes a {@code users} row and an
 * {@code instructors} row in a single transaction through
 * {@link AccountService}; nothing is ever deleted (project_details.md Section
 * 6.8) — "removing" an instructor sets {@code instructors.is_active = 0} and
 * {@code users.is_active = 0} together, and the row stays for every section
 * and grade that references it.</p>
 */
public class InstructorService {

    private final InstructorDAO instructorDao = new InstructorDAO();
    private final UserDAO userDao = new UserDAO();
    private final DepartmentDAO departmentDao = new DepartmentDAO();
    private final AccountService accounts = new AccountService();

    /** Gives access to the connection helpers without exposing a whole data access object. */
    private final AbstractDAO transactions = new AbstractDAO() {
    };

    // ------------------------------------------------------------------ read

    /** Every instructor, for a section combo box or a report that must include inactive staff too. */
    public List<Instructor> listActive() {
        return instructorDao.findAllActive();
    }

    /** Matched against Instructor ID, first name, last name and email. Blank/null returns everyone. */
    public List<Instructor> search(String searchText) {
        if (ValidationUtil.isBlank(searchText)) {
            return instructorDao.findAll();
        }
        String term = searchText.trim().toLowerCase();
        return instructorDao.findAll().stream()
                .filter(i -> String.valueOf(i.getUserId()).contains(term)
                        || i.getFirstName().toLowerCase().contains(term)
                        || i.getLastName().toLowerCase().contains(term)
                        || i.getEmail().toLowerCase().contains(term))
                .toList();
    }

    public Instructor findById(int instructorId) {
        return requireInstructor(instructorId);
    }

    // ------------------------------------------------------------------ create

    /**
     * Creates the login account and the instructor record together.
     *
     * <p>The administrator supplies the personal and departmental details and
     * nothing else: the Instructor ID comes from SQL Server's IDENTITY column,
     * the university email from the instructor's name, and the temporary
     * password from the id once it exists.</p>
     *
     * @param instructor the typed-in details; instructorId, userId,
     *                   employeeNumber and email are ignored on the way in
     * @return the created account's details, to show the administrator once
     */
    public AccountService.NewAccount create(Instructor instructor) {
        validate(instructor);
        requireDepartment(instructor.getDepartmentId());

        instructor.setActive(true);

        Connection connection = transactions.beginTransaction();
        try {
            AccountService.NewAccount account = accounts.createAccount(
                    connection, UserRole.INSTRUCTOR,
                    instructor.getFirstName(), instructor.getLastName());

            instructor.setUserId(account.userId());
            instructor.setEmail(account.email());
            // The retired employee_number column is NOT NULL; see AccountService.
            instructor.setEmployeeNumber(accounts.legacyNumberFor(account.userId()));

            int instructorId = instructorDao.insert(connection, instructor);
            instructor.setInstructorId(instructorId);

            connection.commit();
            return account;
        } catch (SQLException e) {
            transactions.rollbackQuietly(connection);
            throw new ServiceException("The instructor could not be created. No changes were saved.", e);
        } catch (RuntimeException e) {
            transactions.rollbackQuietly(connection);
            throw e;
        } finally {
            transactions.closeQuietly(connection);
        }
    }

    // ------------------------------------------------------------------ update

    /**
     * Updates the editable columns only — never the Instructor ID.
     *
     * <p>A changed university email is written to {@code instructors.email},
     * the one column that holds it, in the same transaction as the rest of the
     * edit — leaving the id, the role and the password untouched.</p>
     */
    public void update(Instructor instructor) {
        Instructor stored = requireInstructor(instructor.getInstructorId());
        validate(instructor);
        requireDepartment(instructor.getDepartmentId());

        // The id is not the administrator's to change.
        instructor.setUserId(stored.getUserId());
        instructor.setEmployeeNumber(stored.getEmployeeNumber());

        Connection connection = transactions.beginTransaction();
        try {
            String email = accounts.validateEditedEmail(connection, instructor.getEmail(),
                    UserRole.INSTRUCTOR, stored.getUserId());
            instructor.setEmail(email);

            instructorDao.update(connection, instructor);

            connection.commit();
        } catch (SQLException e) {
            transactions.rollbackQuietly(connection);
            throw new ServiceException("The instructor could not be updated. No changes were saved.", e);
        } catch (RuntimeException e) {
            transactions.rollbackQuietly(connection);
            throw e;
        } finally {
            transactions.closeQuietly(connection);
        }
    }

    // ------------------------------------------------------------------ soft delete

    /**
     * SOFT DELETE (project_details.md Section 6.8). Nothing is removed:
     * {@code instructors.is_active -> 0} and {@code users.is_active -> 0}
     * together, so the instructor can no longer sign in or be assigned a
     * section, but every section and grade they are already on stays intact.
     */
    public void deactivate(int instructorId) {
        setActiveState(instructorId, false);
    }

    /** Undo of {@link #deactivate}: the instructor and their login are re-enabled. */
    public void reactivate(int instructorId) {
        setActiveState(instructorId, true);
    }

    private void setActiveState(int instructorId, boolean active) {
        Instructor instructor = requireInstructor(instructorId);

        Connection connection = transactions.beginTransaction();
        try {
            instructor.setActive(active);
            instructorDao.update(connection, instructor);
            // The same account, the same Instructor ID, the same address.
            userDao.setActive(connection, instructor.getUserId(), active);
            connection.commit();
        } catch (SQLException e) {
            transactions.rollbackQuietly(connection);
            throw new ServiceException("Could not change the instructor's account state.", e);
        } catch (RuntimeException e) {
            transactions.rollbackQuietly(connection);
            throw e;
        } finally {
            transactions.closeQuietly(connection);
        }
    }

    // ------------------------------------------------------------------ lockout

    /**
     * Undoes an automatic lockout (AuthService.login, after 5 consecutive
     * failed sign-ins): {@code failed_login_attempts} back to 0,
     * {@code is_locked} back to 0, {@code locked_at} back to {@code NULL}.
     * Does not touch the password.
     */
    public void unlock(int instructorId) {
        Instructor instructor = requireInstructor(instructorId);
        userDao.unlock(instructor.getUserId());
    }

    // ------------------------------------------------------------------ password reset

    /**
     * Resets the instructor's password back to the mandatory
     * {@code <Instructor ID>@iNS} default. The account keeps its Instructor ID
     * and its email address.
     *
     * @return the plain-text password to show once to the admin; it is not
     *         stored anywhere, and never reaches the audit log
     */
    public String resetPasswordToDefault(int instructorId) {
        Instructor instructor = requireInstructor(instructorId);
        return accounts.resetPasswordToDefault(instructor.getUserId(), UserRole.INSTRUCTOR);
    }

    // ------------------------------------------------------------------ uniqueness

    /**
     * Is this university email already in use by somebody else?
     *
     * @param excludeUserId the Instructor ID being edited, so an unchanged
     *                      address is not reported as a duplicate
     */
    public boolean emailExists(String email, Integer excludeUserId) {
        return userDao.emailExists(accounts.normalizeEmail(email), excludeUserId);
    }

    // ------------------------------------------------------------------ helpers

    private Instructor requireInstructor(int instructorId) {
        ValidationException.requireId(instructorId, "Instructor");
        return instructorDao.findById(instructorId)
                .orElseThrow(() -> new ServiceException("That instructor record was not found."));
    }

    private void requireDepartment(int departmentId) {
        ValidationException.requireId(departmentId, "Department");
        if (departmentDao.findById(departmentId).isEmpty()) {
            throw new ValidationException("That department does not exist.");
        }
    }

    /**
     * The personal and departmental details only — no Instructor ID check (the
     * database generates it) and no email check (generated on create, judged by
     * {@link AccountService#validateEditedEmail} on edit).
     */
    private void validate(Instructor instructor) {
        if (ValidationUtil.isBlank(instructor.getFirstName()) || !ValidationUtil.maxLength(instructor.getFirstName(), 50)) {
            throw new ValidationException("First name is required (maximum 50 characters).");
        }
        if (ValidationUtil.isBlank(instructor.getLastName()) || !ValidationUtil.maxLength(instructor.getLastName(), 50)) {
            throw new ValidationException("Last name is required (maximum 50 characters).");
        }
        if (ValidationUtil.notBlank(instructor.getPhone()) && !ValidationUtil.isPhone(instructor.getPhone())) {
            throw new ValidationException("Phone number may contain digits, spaces, +, ( ) and -, 7-20 characters.");
        }
        if (!ValidationUtil.maxLength(instructor.getAddress(), 200)) {
            throw new ValidationException("Address must be 200 characters or fewer.");
        }
        ValidationException.requireId(instructor.getDepartmentId(), "Department");
        if (instructor.getAcademicRank() == null) {
            throw new ValidationException("Select an academic rank.");
        }
        LocalDate hireDate = instructor.getHireDate();
        if (hireDate != null && hireDate.isAfter(LocalDate.now())) {
            throw new ValidationException("Hire date cannot be in the future.");
        }
    }
}
