package com.university.service;

import com.university.dao.AbstractDAO;
import com.university.dao.ProgramDAO;
import com.university.dao.StudentDAO;
import com.university.dao.UserDAO;
import com.university.enums.AcademicStanding;
import com.university.enums.StudentStatus;
import com.university.enums.UserRole;
import com.university.model.Program;
import com.university.model.Student;
import com.university.util.ValidationUtil;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;

/**
 * Everything the admin does to student records.
 *
 * <p>Three rules govern this whole class:</p>
 * <ol>
 *   <li>A student's identity is {@code users.user_id}, and the interface calls
 *       it the <b>Student ID</b>. It is generated by SQL Server's IDENTITY
 *       column inside {@link AccountService#createAccount}; nobody types one,
 *       and nothing here computes one.</li>
 *   <li>Creating a student writes TWO rows — {@code users} and {@code students}
 *       — inside one transaction. If either fails, neither is kept, so a login
 *       account without a student behind it cannot exist.</li>
 *   <li>Nothing is ever deleted (project_details.md Section 6.8). "Removing" a
 *       student sets {@code students.status = WITHDRAWN} and
 *       {@code users.is_active = 0}; every enrolment and grade stays put.</li>
 * </ol>
 *
 * <p>{@code cumulative_gpa}, {@code completed_credits} and
 * {@code academic_standing} are cached columns owned by {@link AcademicService}
 * — this class never writes them.</p>
 */
public class StudentService {

    private final StudentDAO studentDao = new StudentDAO();
    private final UserDAO userDao = new UserDAO();
    private final ProgramDAO programDao = new ProgramDAO();
    private final AccountService accounts = new AccountService();

    /** Gives access to the connection helpers without exposing a whole data access object. */
    private final AbstractDAO transactions = new AbstractDAO() {
    };

    // ------------------------------------------------------------------ read

    /** Matched against Student ID, first name, last name and email. Blank/null returns everyone. */
    public List<Student> search(String searchText) {
        return ValidationUtil.isBlank(searchText) ? studentDao.findAll() : studentDao.search(searchText.trim());
    }

    public Student findById(int studentId) {
        return requireStudent(studentId);
    }

    /** The program (major) a student is enrolled in, or null if it can no longer be resolved. */
    public Program programOf(Student student) {
        return programDao.findById(student.getProgramId()).orElse(null);
    }

    /** The live average GPA across every student with completed credits, or null if none yet. */
    public BigDecimal universityAverageGpa() {
        return studentDao.averageCumulativeGpa();
    }

    // ------------------------------------------------------------------ create

    /**
     * Creates the login account and the student record together.
     *
     * <p>The administrator supplies the personal and academic details and
     * nothing else. The Student ID, the university email and the temporary
     * password are all produced here, in this order, because each one depends
     * on the one before it: SQL Server assigns the id, the id makes the
     * password, and the name makes the address.</p>
     *
     * @param student the typed-in details; studentId, userId, studentNumber
     *                and email are ignored on the way in and filled in on the
     *                way out
     * @return the created account's details, to show the administrator once
     */
    public AccountService.NewAccount create(Student student) {
        validate(student);
        requireProgram(student.getProgramId());

        student.setStatus(student.getStatus() == null ? StudentStatus.ACTIVE : student.getStatus());
        student.setAcademicStanding(AcademicStanding.NEW);
        student.setCumulativeGpa(BigDecimal.ZERO);
        student.setCompletedCredits(0);
        student.setProbationCount(0);

        Connection connection = transactions.beginTransaction();
        try {
            AccountService.NewAccount account = accounts.createAccount(
                    connection, UserRole.STUDENT, student.getFirstName(), student.getLastName());

            student.setUserId(account.userId());
            student.setEmail(account.email());
            // The retired student_number column is NOT NULL; see AccountService.
            student.setStudentNumber(accounts.legacyNumberFor(account.userId()));

            int studentId = studentDao.insert(connection, student);
            student.setStudentId(studentId);

            connection.commit();
            return account;
        } catch (SQLException e) {
            transactions.rollbackQuietly(connection);
            throw new ServiceException("The student could not be created. No changes were saved.", e);
        } catch (RuntimeException e) {
            transactions.rollbackQuietly(connection);
            throw e;
        } finally {
            transactions.closeQuietly(connection);
        }
    }

    // ------------------------------------------------------------------ update

    /**
     * Updates the editable columns only. Never touches gpa / credits / standing /
     * probation_count, and never the Student ID.
     *
     * <p>The administrator may put a different university email on the record.
     * It is written to {@code students.email}, the one column that holds it,
     * inside the same transaction as the rest of the edit — and the id, the
     * role and the password are all left exactly as they were.</p>
     */
    public void update(Student student) {
        Student stored = requireStudent(student.getStudentId());
        validate(student);
        requireProgram(student.getProgramId());

        // The id is not the administrator's to change: whatever came back from
        // the form, the account this record belongs to is the stored one.
        student.setUserId(stored.getUserId());
        student.setStudentNumber(stored.getStudentNumber());

        Connection connection = transactions.beginTransaction();
        try {
            String email = accounts.validateEditedEmail(connection, student.getEmail(),
                    UserRole.STUDENT, stored.getUserId());
            student.setEmail(email);

            studentDao.update(connection, student);

            connection.commit();
        } catch (SQLException e) {
            transactions.rollbackQuietly(connection);
            throw new ServiceException("The student could not be updated. No changes were saved.", e);
        } catch (RuntimeException e) {
            transactions.rollbackQuietly(connection);
            throw e;
        } finally {
            transactions.closeQuietly(connection);
        }
    }

    // ------------------------------------------------------------------ soft delete

    /**
     * SOFT DELETE (project_details.md Section 6.8). Nothing is removed:
     * {@code students.status -> WITHDRAWN} (so registration rule R2 blocks them),
     * {@code users.is_active -> 0} (so they can no longer sign in).
     */
    public void deactivate(int studentId) {
        setActiveState(studentId, false);
    }

    /** Undo of {@link #deactivate}: status back to ACTIVE, the login re-enabled. */
    public void reactivate(int studentId) {
        setActiveState(studentId, true);
    }

    private void setActiveState(int studentId, boolean active) {
        Student student = requireStudent(studentId);

        Connection connection = transactions.beginTransaction();
        try {
            student.setStatus(active ? StudentStatus.ACTIVE : StudentStatus.WITHDRAWN);
            studentDao.update(connection, student);
            // The same account, the same Student ID, the same address: only the
            // switch that lets it sign in moves.
            userDao.setActive(connection, student.getUserId(), active);
            connection.commit();
        } catch (SQLException e) {
            transactions.rollbackQuietly(connection);
            throw new ServiceException("Could not change the student's account state.", e);
        } catch (RuntimeException e) {
            transactions.rollbackQuietly(connection);
            throw e;
        } finally {
            transactions.closeQuietly(connection);
        }
    }

    // ------------------------------------------------------------------ password reset

    /**
     * Resets the student's password back to the mandatory {@code <Student ID>@iuL}
     * default. The account keeps its Student ID and its email address.
     *
     * @return the plain-text password to show once to the admin; it is not stored
     *         anywhere, and never reaches the audit log
     */
    public String resetPasswordToDefault(int studentId) {
        Student student = requireStudent(studentId);
        return accounts.resetPasswordToDefault(student.getUserId());
    }

    // ------------------------------------------------------------------ uniqueness

    /**
     * Is this university email already in use by somebody else?
     *
     * @param excludeUserId the Student ID being edited, so an unchanged address
     *                      is not reported as a duplicate; null when creating
     */
    public boolean emailExists(String email, Integer excludeUserId) {
        return userDao.emailExists(accounts.normalizeEmail(email), excludeUserId);
    }

    // ------------------------------------------------------------------ helpers

    private Student requireStudent(int studentId) {
        ValidationException.requireId(studentId, "Student");
        return studentDao.findById(studentId)
                .orElseThrow(() -> new ServiceException("That student record was not found."));
    }

    private void requireProgram(int programId) {
        ValidationException.requireId(programId, "Program");
        if (programDao.findById(programId).isEmpty()) {
            throw new ValidationException("That program does not exist.");
        }
    }

    /**
     * The personal and academic details only. There is deliberately no check
     * on the Student ID (the database generates it) and none on the email
     * either — on create it is generated, and on edit
     * {@link AccountService#validateEditedEmail} judges it against every other
     * account in the system, which this class cannot do on its own.
     */
    private void validate(Student student) {
        if (ValidationUtil.isBlank(student.getFirstName()) || !ValidationUtil.maxLength(student.getFirstName(), 50)) {
            throw new ValidationException("First name is required (maximum 50 characters).");
        }
        if (ValidationUtil.isBlank(student.getLastName()) || !ValidationUtil.maxLength(student.getLastName(), 50)) {
            throw new ValidationException("Last name is required (maximum 50 characters).");
        }
        if (ValidationUtil.notBlank(student.getPhone()) && !ValidationUtil.isPhone(student.getPhone())) {
            throw new ValidationException("Phone number may contain digits, spaces, +, ( ) and -, 7-20 characters.");
        }
        LocalDate dob = student.getDateOfBirth();
        if (dob != null) {
            if (!dob.isBefore(LocalDate.now())) {
                throw new ValidationException("Date of birth must be in the past.");
            }
            if (dob.isAfter(LocalDate.now().minusYears(15))) {
                throw new ValidationException("The student must be at least 15 years old.");
            }
        }
        if (!ValidationUtil.maxLength(student.getAddress(), 200)) {
            throw new ValidationException("Address must be 200 characters or fewer.");
        }
        ValidationException.requireId(student.getProgramId(), "Program");
        if (student.getAdmissionDate() == null) {
            throw new ValidationException("Admission date is required.");
        }
        if (student.getAdmissionDate().isAfter(LocalDate.now())) {
            throw new ValidationException("Admission date cannot be in the future.");
        }
    }
}
